package main

// <xbar.title>In My Dream I Hit The Bay</xbar.title>
// <xbar.version>v1.0</xbar.version>
// <xbar.author>Hsing-Yu Chen</xbar.author>
// <xbar.author.github>davidhsingyuchen</xbar.author.github>
// <xbar.desc>This plugin is used to produce the MV of In My Dream I Hit The Bay.</xbar.desc>
// <xbar.image>https://img.favpng.com/11/18/10/tightrope-walking-computer-icons-youtube-png-favpng-qcQdAyeKgpbCPdmQeaU9757iD.jpg</xbar.image>
// <xbar.dependencies>go</xbar.dependencies>
// <xbar.abouturl>https://github.com/davidhsingyuchen/xbar-plugin-in-my-dream-i-hit-the-bay</xbar.abouturl>

import (
	"fmt"
	"log"
	"math/rand"
	"os"
)

const (
	// https://img.favpng.com/11/18/10/tightrope-walking-computer-icons-youtube-png-favpng-qcQdAyeKgpbCPdmQeaU9757iD.jpg
	manWalkingOnATightropeB64Path = `man-walking-on-a-tightrope.B64`
	// It is generated by feeding https://commons.wikimedia.org/wiki/File:Stack_Overflow_icon.svg
	// to https://manytools.org/hacker-tools/convert-images-to-ascii-art/.
	stackOverflowLogoPath = "stack-overflow-logo.ans"
	secondEntryText       = "thoughts"
)

var firstEntryAlternatingTexts = []string{"Everything will be fine.", "Nah, it's just a fairy tale."}

func mustBeNil(err error, msg string) {
	if err != nil {
		log.Fatalf("%s: %v", msg, err)
	}
}

func printThumbnail(path string) {
	thumbnail, err := os.ReadFile(path)
	mustBeNil(err, "failed to read the thumbnail from the file system")
	fmt.Printf("| templateImage=%s", string(thumbnail))
}

func printFirstEntry(texts []string) {
	idx := rand.Intn(len(texts))
	fmt.Println(texts[idx])
}

func printSecondEntry(text, imgPath string) {	
	fmt.Println(text)

	img, err := os.ReadFile(imgPath)
	mustBeNil(err, "failed to read the image for the second entry from the file system")

	str := string(img)
	start := 0
	for i := 0; i < len(str); i++ {
		if str[i] == '\n' {
			fmt.Printf("--%s\n", str[start:i])
			start = i + 1
		}
	}
}

func printSeparator() {
	fmt.Println("---")
}

func main() {
	printThumbnail(manWalkingOnATightropeB64Path)
	printSeparator()
	printFirstEntry(firstEntryAlternatingTexts)
	printSeparator()
	printSecondEntry(secondEntryText, stackOverflowLogoPath)
}
